CREATE TABLE seats
(
    id SERIAL PRIMARY KEY,
    number INT NOT NULL,
    is_booked BOOLEAN NOT NULL,
    hall_id INT NOT NULL,
    FOREIGN KEY (hall_id) REFERENCES halls(id) ON DELETE CASCADE
);

INSERT INTO seats (number, is_booked, hall_id)
VALUES (1, false, 1),
       (2, false, 1),
       (3, false, 1),
       (4, false, 1),
       (5, false, 1),
       (6, false, 1),
       (7, false, 1),
       (8, false, 1),
       (9, false, 1),
       (10, false, 1),
       (11, false, 1),
       (12, false, 1),
       (13, false, 1),
       (14, false, 1),
       (15, false, 1),
       (1, false, 2),
       (2, false, 2),
       (3, false, 2),
       (4, false, 2),
       (5, false, 2),
       (6, false, 2),
       (7, false, 2),
       (8, false, 2),
       (9, false, 2),
       (10, false, 2),
       (1, false, 3),
       (2, false, 3),
       (3, false, 3),
       (4, false, 3),
       (5, false, 3),
       (6, false, 3),
       (7, false, 3),
       (8, false, 3),
       (9, false, 3),
       (10, false, 3),
       (11, false, 3),
       (12, false, 3),
       (1, false, 4),
       (2, false, 4),
       (3, false, 4),
       (4, false, 4),
       (5, false, 4),
       (6, false, 4),
       (7, false, 4),
       (8, false, 4),
       (9, false, 4),
       (10, false, 4),
       (11, false, 4),
       (12, false, 4);

