name: Build application

on:
  workflow_call:
    secrets:
      REPSY_USER:
      REPSY_PASSWORD:
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup build
        uses: gradle/gradle-build-action@v2
        env:
          REPSY_USER: ${{ secrets.REPSY_USER }}
          REPSY_PASSWORD: ${{ secrets.REPSY_PASSWORD }}

      - name: Execute gradle assemble
        env:
          REPSY_USER: ${{ secrets.REPSY_USER }}
          REPSY_PASSWORD: ${{ secrets.REPSY_PASSWORD }}
        run: ./gradlew assemble
