name: Publish Ciphers Library

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Publish to Maven Repository
        env:
          REPSY_USER: ${{ secrets.REPSY_USER }}
          REPSY_PASSWORD: ${{ secrets.REPSY_PASSWORD }}
        run: ./gradlew publish
