name: Collect Test Report

on:
  workflow_call:

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Collect test report
        run: ./gradlew jacocoTestReport
