name: Check code quality via SonarLint

on:
  workflow_call:

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: SonarLint for main with Gradle
        run: ./gradlew sonarlintMain
